### PR TITLE
feat(exchange app): Update frontend for graceful network handling

### PR DESCRIPTION
**Pull request by m-czernek**
This PR adds the following:

- New environment variable `REACT_APP_NEWS_ENABLED` was added to enable/disable news tab. This is because it was difficult to always remove it manually
- Requests now have retries (3 by default)
- Requests now have timeouts (3000 ms by default)
- Error is being propagated into the frontend, to the user

This new version is released as `quay.io/redhattraining/ossm-frontend:3.0` and is used in end of chapter lab of ch06.

### CODE REVIEW

**Comment by someth2say** [comment]
Didn't try, but looks good to me.
My only concern is: why are we releasing this as a new image?
If changes are backward compatible, then go and just update v1.0 so everyone makes use of the changes.
If changes are not compatible, we need to keep both version's code (different folders?)

**Comment by m-czernek** [comment]
We aren't releasing this as a new image, we are releasing this as a new version of our image.

Version 1.0 shows an application that deals poorly with failed network calls.
Version 3.0 shows an application that handles failed network calls gracefully.

There was no agreement on keeping multiple versions of the same code in different directories AFAIK. I'll think about this and see how we can deal with this. That said, for all intents and purposes, chapters other than 06 may use either 1.0 or 3.0 interchangeably.

**Comment by someth2say** [comment]
Yes, true, it's a new tag, not a new image.
Anyway, my concern is: what if different sections use different tags, and we found the situation that we need to fix the code in both versions?
We will not be able to re-create the v1 tag, as the code has been overwritten.

I agree we didn't agree on versions-per-folder vs versions-per-branch. 
My question is: shall we solve this agreement now, or can we just overwrite v1.0?

**Comment by m-czernek** [comment]
I have created all versions. This is an ugly solution, but suitable for learning purposes, I agree. 

We cannot overwrite 1.0, since ch6 is using it.

**Comment by m-czernek** [comment]
Ch06 merged. Since I've created multiple directories (one for each version), we should be good to go. Merging here as well.

**Pull request merged**
